language: java
# set up the vm for android compilation
before_install:
  - wget http://dl.google.com/android/android-sdk_r20.0.3-linux.tgz
  - tar -zxf android-sdk_r20.0.3-linux.tgz
  - export ANDROID_HOME=~/builds/MobileGurus/Travis-CI/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --filter 1,3,10 --no-ui --force
# compile
script:
  - ant release
# upload finished product
after_script:
  - git clone https://github.com/FloydPink-Public/Travis-CI.git
  - cd Travis-CI
  - cp ../bin/TravisCI-release.apk .
  - git add .
  - git commit -a -m "Committed from CI (build number - $TRAVIS_JOB_ID)"
  - git push --repo https://floydpink-public:Public-FloydPink@github.com/FloydPink-Public/Travis-CI.git
